apiVersion: batch/v1
kind: Job
metadata:
  name: cyclonus
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - ./cyclonus
        - generate
        - --cleanup-namespaces=true
        name: cyclonus
        imagePullPolicy: IfNotPresent
        image: mfenwick100/cyclonus:latest
      serviceAccount: cyclonus
